version: "3"

services:
  webserver:
    build: .
    container_name: 'testsit-web'
    restart: 'always'
    ports:
      - "3000:3000"
    links:
      - mariadb
    #volumes:
    #  - ${DOCUMENT_ROOT-.}:/usr/src/app
    environment:
      - DATABASE_URL=mysql://testsit:testsit@mariadb:3306/testsit_database
  mariadb:
    image: mariadb:10.3
    container_name: 'testsit-db'
    restart: 'always'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: testsit_database
      MYSQL_USER: testsit
      MYSQL_PASSWORD: testsit
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'testsit-phpmyadmin'
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions
